#!/usr/bin/env bash
# Display information about subdomains for DuckDNS

get_subdomain_info() {
    local base_domain=$1
    local subdomain=$2
    local full_domain
    
    case $subdomain in
        "www")
            full_domain="${base_domain}-www.duckdns.org"
            ;;
        "lb-01")
            full_domain="${base_domain}-lb01.duckdns.org"
            ;;
        "web-01")
            full_domain="${base_domain}-web01.duckdns.org"
            ;;
        "web-02")
            full_domain="${base_domain}-web02.duckdns.org"
            ;;
        *)
            full_domain="${subdomain}.${base_domain}"
            ;;
    esac
    
    local result
    local record_type
    local destination
    
    result=$(dig "$full_domain" | grep -A1 'ANSWER SECTION:' | tail -1)
    record_type=$(echo "$result" | awk '{print $4}')
    destination=$(echo "$result" | awk '{print $5}')
    
    if [ -n "$destination" ]; then
        echo "The subdomain $subdomain is a $record_type record and points to $destination"
    fi
}

base_domain=$(echo "$1" | sed 's/.duckdns.org//')
subdomain=$2

if [ -z "$subdomain" ]; then
    get_subdomain_info "$base_domain" "www"
    get_subdomain_info "$base_domain" "lb-01"
    get_subdomain_info "$base_domain" "web-01"
    get_subdomain_info "$base_domain" "web-02"
else
    get_subdomain_info "$base_domain" "$subdomain"
fi
